//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Teacher
    {
          [Required(ErrorMessage="This field is required")]
        public int Tid { get; set; }
          [Required(ErrorMessage = "This field is required")]
          [Display(Name = "Teacher's name")]
        public string Name { get; set; }
          [Required(ErrorMessage = "This field is required")]
      //    [StringLength(15, ErrorMessage = "Max 11 digits", MinimumLength = 7)]
        public Nullable<int> PhoneNo { get; set; }
          [Required(ErrorMessage = "This field is required")]
        public string Description { get; set; }
          [Required(ErrorMessage = "This field is required")]
        public string Image { get; set; }
          [Required(ErrorMessage = "This field is required")]
          [DataType(DataType.EmailAddress, ErrorMessage = "This must be a valid email address")]
        public string Email { get; set; }
          [Required(ErrorMessage = "This field is required")]
          [DataType(DataType.Password)]
          [Display(Name = "Password")]
      //    [StringLength(15, ErrorMessage = "Max 8 digits", MinimumLength = 6)]
        public string Password { get; set; }
    }
}
